import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:hilway/core/constants/app_constants.dart';
import 'package:hilway/core/models/mood_log.dart';
import 'package:hilway/core/models/stress_rating.dart';
import 'package:hilway/core/models/chat_message.dart';
import 'package:hilway/core/models/planner_entry.dart';
import 'package:hilway/core/models/assessment_result.dart';

class HiveService {
  HiveService._();

  static const _encryptionKeyName = 'hive_encryption_key';
  static const _secureStorage = FlutterSecureStorage(
    aOptions: AndroidOptions(encryptedSharedPreferences: true),
  );

  static Future<void> init() async {
    await Hive.initFlutter();

    // Register all Hive adapters (generated by build_runner)
    Hive.registerAdapter(MoodLogAdapter());
    Hive.registerAdapter(StressRatingAdapter());
    Hive.registerAdapter(ChatMessageAdapter());
    Hive.registerAdapter(PlannerEntryAdapter());
    Hive.registerAdapter(AssessmentResultAdapter());

    final encryptionKey = await _getOrCreateEncryptionKey();
    await _openBoxes(encryptionKey);
  }

  static Future<List<int>> _getOrCreateEncryptionKey() async {
    final existingKey = await _secureStorage.read(key: _encryptionKeyName);

    if (existingKey != null) {
      return existingKey.codeUnits;
    }

    final newKey = Hive.generateSecureKey();
    await _secureStorage.write(
      key: _encryptionKeyName,
      value: String.fromCharCodes(newKey),
    );
    return newKey;
  }

  static Future<void> _openBoxes(List<int> encryptionKey) async {
    final cipher = HiveAesCipher(encryptionKey);

    // Encrypted boxes — HIGH sensitivity (chat, journal/settings)
    await Hive.openBox<ChatMessage>(
      AppConstants.boxChatMessages,
      encryptionCipher: cipher,
    );
    await Hive.openBox(
      AppConstants.boxSettings,
      encryptionCipher: cipher,
    );

    // Unencrypted boxes — MEDIUM/LOW sensitivity
    await Hive.openBox<MoodLog>(AppConstants.boxMoodLogs);
    await Hive.openBox<StressRating>(AppConstants.boxStressRatings);
    await Hive.openBox<PlannerEntry>(AppConstants.boxPlannerEntries);
    await Hive.openBox<AssessmentResult>(AppConstants.boxAssessments);
    await Hive.openBox(AppConstants.boxUserCache);
  }

  // ── Box accessors ─────────────────────────────────────────────────────────
  static Box<MoodLog> get moodBox =>
      Hive.box<MoodLog>(AppConstants.boxMoodLogs);

  static Box<StressRating> get stressBox =>
      Hive.box<StressRating>(AppConstants.boxStressRatings);

  static Box<ChatMessage> get chatBox =>
      Hive.box<ChatMessage>(AppConstants.boxChatMessages);

  static Box<PlannerEntry> get plannerBox =>
      Hive.box<PlannerEntry>(AppConstants.boxPlannerEntries);

  static Box<AssessmentResult> get assessmentBox =>
      Hive.box<AssessmentResult>(AppConstants.boxAssessments);

  static Box get settingsBox =>
      Hive.box(AppConstants.boxSettings);

  static Box get userCacheBox =>
      Hive.box(AppConstants.boxUserCache);

  // ── Generic helpers ───────────────────────────────────────────────────────
  static Box getBox(String boxName) => Hive.box(boxName);

  static Future<void> clearBox(String boxName) async {
    await Hive.box(boxName).clear();
  }

  static Future<void> closeAll() async {
    await Hive.close();
  }

  static Future<void> deleteAllData() async {
    for (final boxName in [
      AppConstants.boxMoodLogs,
      AppConstants.boxStressRatings,
      AppConstants.boxChatMessages,
      AppConstants.boxPlannerEntries,
      AppConstants.boxAssessments,
      AppConstants.boxSettings,
      AppConstants.boxUserCache,
    ]) {
      if (Hive.isBoxOpen(boxName)) {
        await Hive.box(boxName).deleteFromDisk();
      }
    }
    await _secureStorage.delete(key: _encryptionKeyName);
  }
}